<?xml version="1.0" encoding="utf-8"?><Database Name="dnndev_v902.me" Class="kk_aj_ArrangemangLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ASUSI7-ANDREAS\SQLEXPRESS;Initial Catalog=dnndev_v902.me;Persist Security Info=True;User ID=dnndev_v902.me" SettingsObjectName="KulturkatalogenArrangemang.My.MySettings" SettingsPropertyName="dnndev_v902_meConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.kk_aj_tbl_arridtoContent" Member="kk_aj_tbl_arridtoContents">
    <Type Name="kk_aj_tbl_arridtoContent">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contentid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_content" Member="kk_aj_tbl_contents">
    <Type Name="kk_aj_tbl_content">
      <Column Name="Contentid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ImageFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ImageFotograf" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MovieClipFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MovieClipAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MovieClipCredits" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_fakta" Member="kk_aj_tbl_faktas">
    <Type Name="kk_aj_tbl_fakta">
      <Column Name="faktaid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="faktatypid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="faktaValue" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Utovare" Member="kk_aj_tbl_Utovares">
    <Type Name="kk_aj_tbl_Utovare">
      <Column Name="UtovarID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Fornamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Telefonnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Postnr" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ort" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Epost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Kommun" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Hemsida" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_ArrangemangStatus" Member="kk_aj_tbl_ArrangemangStatus">
    <Type Name="kk_aj_tbl_ArrangemangStatus">
      <Column Name="ArrangemangStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Arrangemangtyp" Member="kk_aj_tbl_Arrangemangtyps">
    <Type Name="kk_aj_tbl_Arrangemangtyp">
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrangemangtyp" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_faktatyp" Member="kk_aj_tbl_faktatyps">
    <Type Name="kk_aj_tbl_faktatyp">
      <Column Name="faktatypid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Faktarubrik" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Konstformtyp" Member="kk_aj_tbl_Konstformtyps">
    <Type Name="kk_aj_tbl_Konstformtyp">
      <Column Name="KonstformID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="dnnRollid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsTrialUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsOwner" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_MediaTyp" Member="kk_aj_tbl_MediaTyps">
    <Type Name="kk_aj_tbl_MediaTyp">
      <Column Name="mediatypID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mediatyp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_ArridToArrGrupp" Member="kk_aj_tbl_ArridToArrGrupps">
    <Type Name="kk_aj_tbl_ArridToArrGrupp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="arrgruppid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_ArrGrupp" Member="kk_aj_tbl_ArrGrupps">
    <Type Name="kk_aj_tbl_ArrGrupp">
      <Column Name="arrgruppID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrgrupptitel" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Media" Member="kk_aj_tbl_Medias">
    <Type Name="kk_aj_tbl_Media">
      <Column Name="mediaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mediaUrl" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="mediaFileName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="mediaSize" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="mediaAlt" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="mediaFoto" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="mediaTyp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mediaVald" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="mediaTitle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="mediaBeskrivning" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="mediaLink" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="sortering" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Kontakt" Member="kk_aj_tbl_Kontakts">
    <Type Name="kk_aj_tbl_Kontakt">
      <Column Name="kontaktid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fornamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Epost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Arrangemang" Member="kk_aj_tbl_Arrangemangs">
    <Type Name="kk_aj_tbl_Arrangemang">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminuserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArrangemangStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VisningsPeriod" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="inlagddatum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="konstform2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="konstform3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kontaktid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.kk_aj_proc_getStatusCount" Method="kk_aj_proc_getStatusCount">
    <Parameter Name="arrStatusTyp" Type="System.Int32" DbType="Int" />
    <Parameter Name="rolltypAdmin" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll1" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll2" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll3" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll4" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll5" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll6" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll7" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll8" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll9" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll10" Type="System.Int32" DbType="Int" />
    <Parameter Name="visningsperiod" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="kk_aj_proc_getStatusCountResult">
      <Column Name="antal" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_MapRollToKonstform" Method="kk_aj_proc_MapRollToKonstform">
    <Parameter Name="userid" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_MapRollToKonstformResult">
      <Column Name="KonstformID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_getfaktabyarrid" Method="kk_aj_proc_getfaktabyarrid">
    <Parameter Name="arrid" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_getfaktabyarridResult">
      <Column Name="Faktarubrik" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="faktaValue" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="faktaid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="faktatypid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_Getarrby_Latest" Method="kk_aj_proc_Getarrby_Latest">
    <Parameter Name="arrid" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_Getarrby_LatestResult">
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ImageFotograf" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ImageFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_GetArrby_LatestEvent" Method="kk_aj_proc_GetArrby_LatestEvent">
    <Parameter Name="rolltypAdmin" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll1" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll2" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll3" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll4" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll5" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll6" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll7" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll8" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll9" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll10" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll11" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll12" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll13" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll14" Type="System.Int32" DbType="Int" />
    <Parameter Name="visningsperiod" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="kk_aj_proc_GetArrby_LatestEventResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logtyp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statustyp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dnnRollid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_GetArrby_ArrStatus" Method="kk_aj_proc_GetArrby_ArrStatus">
    <Parameter Name="arrStatusTyp" Type="System.Int32" DbType="Int" />
    <Parameter Name="rolltypAdmin" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll1" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll2" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll3" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll4" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll5" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll6" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll7" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll8" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll9" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll10" Type="System.Int32" DbType="Int" />
    <Parameter Name="visningsperiod" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="kk_aj_proc_GetArrby_ArrStatusResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UnderRubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="arrangemangtyp" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_getFilterFaktabyArrid" Method="kk_aj_proc_getFilterFaktabyArrid">
    <Parameter Name="arrid" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_getFilterFaktabyArridResult">
      <Column Name="faktatypid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="faktaValue" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_GetArrDetails" Method="kk_aj_proc_GetArrDetails">
    <Parameter Name="arrID" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_GetArrDetailsResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VisningsPeriod" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AdminuserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Fornamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Telefonnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Postnr" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ort" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Epost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Kommun" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Hemsida" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="arrangemangtyp" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ImageFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ImageFotograf" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MovieClipFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MovieClipAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MovieClipCredits" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ArrangemangStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kontaktfornamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kontaktefternamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kontaktepost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="konstform2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="konstform3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_Search_freetext" Method="kk_aj_proc_Search_freetext">
    <Parameter Name="searchstr" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="pubyesno" Type="System.String" DbType="NVarChar(3)" />
    <ElementType Name="kk_aj_proc_Search_freetextResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="startyear" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="stoppyear" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="konstform2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="konstform3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_search" Method="kk_aj_proc_search">
    <Parameter Name="arrtypid" Type="System.Int32" DbType="Int" />
    <Parameter Name="konstartid" Type="System.Int32" DbType="Int" />
    <Parameter Name="startyear" Type="System.Int32" DbType="Int" />
    <Parameter Name="stoppyear" Type="System.Int32" DbType="Int" />
    <Parameter Name="pubyesno" Type="System.String" DbType="NVarChar(3)" />
    <ElementType Name="kk_aj_proc_searchResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="startyear" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="stoppyear" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="konstform2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="konstform3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_FormUtovareSearch" Method="kk_aj_proc_FormUtovareSearch">
    <Parameter Name="epost" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="postnr" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="kk_aj_proc_FormUtovareSearchResult">
      <Column Name="UtovarID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Fornamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Telefonnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Postnr" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ort" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Epost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Kommun" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Hemsida" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ovrigt" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Bild" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_GetArrGranskaDetails" Method="kk_aj_proc_GetArrGranskaDetails">
    <Parameter Name="arrID" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_GetArrGranskaDetailsResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VisningsPeriod" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AdminuserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Fornamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Telefonnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Postnr" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ort" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Epost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Kommun" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Hemsida" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="arrangemangtyp" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ImageFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ImageFotograf" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MovieClipFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MovieClipAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MovieClipCredits" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ArrangemangStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kontaktfornamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kontaktefternamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kontaktepost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="konstform2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="konstform3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_GetArrby_Search" Method="kk_aj_proc_GetArrby_Search">
    <Parameter Name="searchval" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="arrStatusTyp" Type="System.Int32" DbType="Int" />
    <Parameter Name="rolltypAdmin" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll1" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll2" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll3" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll4" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll5" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll6" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll7" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll8" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll9" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll10" Type="System.Int32" DbType="Int" />
    <Parameter Name="visningsperiod" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="kk_aj_proc_GetArrby_SearchResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="arrangemangtyp" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ArrangemangStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_GetArrBy_Utovare" Method="kk_aj_proc_GetArrBy_Utovare">
    <Parameter Name="utovarid" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_GetArrBy_UtovareResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VisningsPeriod" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AdminuserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Fornamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Telefonnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Postnr" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ort" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Epost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Kommun" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Hemsida" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="arrangemangtyp" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ImageFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ImageFotograf" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MovieClipFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MovieClipAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MovieClipCredits" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ArrangemangStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="arrgruppid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="konstform2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="konstform3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>